modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="" #optional
authors="" #optional

[[mods]] #mandatory
modId="villmark" #mandatory
version="0.1.0" #mandatory
displayName="Vill Mark" #mandatory
description='''
It's great.
Thank You PewDiePie
'''

[[dependencies.villmark]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.villmark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"